# Generated by Django 5.1.2 on 2024-12-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_reception_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='cpf',
            field=models.CharField(max_length=13, unique=True, verbose_name='CPF'),
        ),
    ]
