# Generated by Django 5.1.2 on 2024-12-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pacient_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
