# Generated by Django 5.1.2 on 2024-12-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_pacient_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='priority',
        ),
        migrations.AddField(
            model_name='queue',
            name='comorbidities',
            field=models.CharField(blank=True, choices=[('visuais', 'Necessidades Visuais'), ('fisicas', 'Necessidades Físicas'), ('mental', 'Necessidades Mentais'), ('oncologico', 'Paciente Oncológico'), ('outros', 'Outros')], max_length=20, null=True),
        ),
    ]
